### ISSUE TITLE
Supporting tunnel option in Relay

### ISSUE THREAD

**Issue by jetxr** [getsentry/relay#1024]
Currently [a script is needed](https://docs.sentry.io/platforms/javascript/troubleshooting/#using-the-tunnel-option) when using a tunnel option with the JS SDK.

Looks like the scripts POSTs the received data to `/envelope/` endpoint.

Is it possible to configure the tunnel directly in Relay? Or is the script needed with Relay as well?

**Comment by jan-auer** [comment]
Thanks, this is possible in principle, and we're considering to add an option for specifying a custom tunnel endpoint that Relay listens to in addition to the regular `/api/<id>/envelope/` endpoint. However, I would like to point out that you would currently have to host Relay on a separate domain, or put a proxy in front of Relay to route requests to that endpoint.

**Comment by jetxr** [comment]
> we're considering to add an option for specifying a custom tunnel endpoint

That would be awesome!

Yep, will try and figure out setting up the script. The good thing with Relay is that it runs without any additional runtime, and this script will  need setting up PHP, etc.

**Comment by jan-auer** [comment]
We're in the process of updating and expanding our docs around that. You can add an equivalent script in any other language, or even add an endpoint to your existing server/API. As long as it forwards the entire request to Sentry's envelope endpoint (including your project ID), you should be good. If it's an option, you could even do that on your reverse-proxy or load balancer if you have one. 

May I ask, how would you run Relay? Would that be on a separate domain, on a sub-path, would you have routing in front of Relay, ...?

**Comment by jetxr** [comment]
I'm using it in Docker along with Traefik, like so:

```yaml
version: "3.8"

networks:
  traefik:
    external:
      name: traefik_default

services:
  relay:
    image: getsentry/relay:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./config:/work/.relay
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentryrelay.rule=Host(${ACCESS_DOMAINS})"
      - "traefik.http.routers.sentryrelay.entrypoints=websecure,web"
      - "traefik.http.routers.sentryrelay.service=service-sentryrelay"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.sentryrelay.tls.certresolver=letsencrypt"
      - "traefik.http.services.service-sentryrelay.loadbalancer.server.port=3000"
```

I'm guessing it's possible to configure forwarding the whole request in [Traefik directly](https://doc.traefik.io/traefik/middlewares/redirectregex/). I'll try and test it..
