### ISSUE TITLE
relay shouldn't return HTTP 200 OK to POS requests when it's not registered on a sentry

### ISSUE THREAD

**Issue by drook** [getsentry/relay#1098]
### Environment
Relay 21.8.0
on-premises setup.
multiple relays pointing to one sentry/snuba.

Relay has 2 OOB healthcheck URLs:

- /api/relay/healthcheck/live/ - generally a redundant one. reverse-rpxy could detect if a particular relay is down in a pool merely if it's now answering.
- /api/relay/healthcheck/ready/ - decent one, but OOB only.

The thing is, when relay is not registered on sentry, it keeps returning 200s HTTP statuses to POST /api/... , making reverse proxy think that the cain is okay. This makes the engineer to implement OOB check using haproxy (or subscribe to nginx played plan to use it's OOB hc). This behavior is there frfom 0.10.x.

In fact, when not registered, relay should not return HTTP 200 status and, for instance, should return 503. This will make the OOB hc redundant and will simplify the HA reverse-proxy configurations, since nginx is using inband health-checks, sequentially trying all the upstream servers in a pool until it will get e healthy answer.

**Comment by jjbayer** [comment]
@drook I believe this should only happen when `relay.ready: always` is set in the configuration (default is "authenticated"), could you check your config for that flag?

See also https://github.com/getsentry/relay/pull/989.

**Comment by drook** [comment]
Actually it's on its default:

````
---
relay:
  upstream: "http://10.100.33.18:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: TRACE
  format: simplified
  log_failed_payloads: true
  enabled: true
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "10.100.33.7:9092"}
  redis: redis://10.100.33.5:6379
limits:
  max_thread_count: 8
````
