### ISSUE TITLE
Running Sentry Relay on kubernetes - ERROR: bind to interface failed

### ISSUE THREAD

**Issue by laurenz-glueck** [getsentry/relay#1172]
I'm currently trying to setup a Sentry Relay in our kubernetes cluster.

I want to use the relay in `proxy` mode for Sentry SaaS (sentry.io) and have created a small helm chart for that.

When I now deploy the chart, I get this error during the container start:
`ERROR: bind to interface failed caused by: Permission denied (os error 13)`

![Screenshot 2022-01-27 at 15 15 37](https://user-images.githubusercontent.com/2734232/151376606-07ca3d58-f759-4baa-a703-97462aaa3d46.png)

My chart in general is pretty simple (for testing purpose) - I only have one deployment for the relay container:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-relay
  labels:
    app: sentry-relay
spec:
  selector:
    matchLabels:
      app: sentry-relay
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry-relay
    spec:
      containers:
        - name: sentry-relay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - "run"
          ports:
            - containerPort: {{ .Values.relay.port }}
          volumeMounts:
            - name: config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: sentry-relay
            defaultMode: 0644
```

And the config map for the relay configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry-relay
  labels:
    app: sentry-relay
data:
  config.yml: |
    ---
    relay:
      mode: {{ .Values.relay.mode }}
      upstream: "https://sentry.io/"
      host: 0.0.0.0
      port: {{ .Values.relay.port }}

```

I am happy for any tips because I have no idea why the relay is not starting...
