### ISSUE TITLE
Getting invalid project ID error, but the project ID is not invalid

### ISSUE THREAD

**Issue by kennedyjosh** [getsentry/relay#1511]
### Environment

Latest version fetched from a docker compose file:
```
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - relay-network
    environment:
      - ENV=production
      - APPLICATION_URL=http://relay
  relay:
    image: getsentry/relay
    container_name: relay
    command: ["run", "--config", "/etc/relay/"]
    volumes:
      - /home/ec2-user/config/:/etc/relay/
    expose:
      - "80"
    networks:
      - relay-network

networks:
  relay-network:
```

config file:
```
---
relay:
  mode: static
  upstream: "https://sentry.io/"
  host: 0.0.0.0
  port: 80
  tls_port: ~
  tls_identity_path: ~
  tls_identity_password: ~
``` 

### Steps to Reproduce

1. Start both containers using `docker compose up`
2. `export SENTRY_DSN=https://ed03b5weovnv103875f8f2c93a45790@sentry.mydomain/1430973` 
    * The actual values have been changed to protect privacy
3. `sentry-cli send-event -m "test 123"`

### Expected Result

* I expect traffic to be routed through the nginx container to the relay container.
* I expect the message to then be sent through to sentry, and to be able to view it on sentry.io 

### Actual Result

Traffic is successfully routed to the relay container. However, the envelope is then dropped with reason: `invalid data (project_id)`

Logs:
```
relay  | 2022-10-03T21:15:16Z [relay_server::actors::project] DEBUG: project ed03b5weovnv103875f8f2c93a45790 state requested
relay  | 2022-10-03T21:15:16Z [relay_server::endpoints::common] TRACE: queueing envelope
relay  | 2022-10-03T21:15:16Z [relay_server::actors::project] DEBUG: project ed03b5weovnv103875f8f2c93a45790 state request amended
relay  | 2022-10-03T21:15:16Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: invalid data (project_id)
relay  | 2022-10-03T21:15:16Z [relay_server::actors::project] DEBUG: project state ed03b5weovnv103875f8f2c93a45790 updated
relay  | 2022-10-03T21:15:16Z [relay_server::actors::outcome_aggregator] TRACE: Outcome aggregation requested: TrackOutcome { timestamp: 2022-10-03T21:15:16.311612964Z, scoping: Scoping { organization_id: 0, project_id: ProjectId(1430973), project_key: ProjectKey("ed03b5weovnv103875f8f2c93a45790"), key_id: None }, outcome: Invalid(ProjectId), event_id: Some(EventId(cb371457-1745-4b31-8260-8f3bf7d7baa2)), remote_addr: Some(172.18.0.3), category: Error, quantity: 1 }
relay  | 2022-10-03T21:15:16Z [relay_server::actors::outcome_aggregator] TRACE: Erasing event_id, remote_addr for aggregation: TrackOutcome { timestamp: 2022-10-03T21:15:16.311612964Z, scoping: Scoping { organization_id: 0, project_id: ProjectId(1430973), project_key: ProjectKey("ed03b5weovnv103875f8f2c93a45790"), key_id: None }, outcome: Invalid(ProjectId), event_id: Some(EventId(cb371457-1745-4b31-8260-8f3bf7d7baa2)), remote_addr: Some(172.18.0.3), category: Error, quantity: 1 }
```

My initial thought might be that the relay container could not communicate with the internet, and thus could not properly resolve the project ID. This is not the case:
```
$ sudo docker exec -it relay curl http://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

I've also double-checked that the Project ID is indeed correct:
1. `SENTRY_DSN` to the link from `Settings -> MyProject -> Client Keys` on sentry.io works as intended. 
2. `sentry-cli send-event -m "test 321"`
3. Test message appears on sentry.io
