### ISSUE TITLE
Relay redis issue: invalid UTF-8

### ISSUE THREAD

**Issue by n0tsaved** [getsentry/relay#1580]
Hello,
I'm seeing lots of these logs in my relay nodes (managed mode)
```
2022-11-10T11:28:24Z [relay_server::actors::project] DEBUG: project 4b18642b5ab24871bd6bf5804f0dae5a state request amended
2022-11-10T11:28:24Z [relay_server::actors::project_redis] ERROR: Failed to fetch project from Redis: failed to talk to redis
  caused by: failed to communicate with redis
  caused by: Invalid UTF-8
2022-11-10T11:28:24Z [relay_server::actors::project_upstream] DEBUG: updating project states for 1/1 projects (attempt 1)
2022-11-10T11:28:24Z [relay_server::actors::project_upstream] DEBUG: sending request of size 1
2022-11-10T11:28:24Z [relay_server::actors::project] DEBUG: project state 4b18642b5ab24871bd6bf5804f0dae5a updated
```
I don't see evident problems in my sentry infrastructure, but at some point the memory usage of redis dropped.
From the collected redis stats I can see an average of ~20k items.
It just seems strange since we have almost 100 active projects and from the haproxy stats I can see that we are receiving ~20k events per minute so I'm afraid we might be missing something.

Suggestions on how to debug this?

**Comment by jan-auer** [comment]
You're mentioning that you run Relays in managed mode. Do you have the affected instances configured as part of a sentry self-hosted deployment, or as an additional proxy in front of either sentry.io or a self-hosted instance?

Ideally, please share the contents of `config.yml` with us, so we can check the configuration.

**Comment by n0tsaved** [comment]
Hello, thanks for the response.
I run my own self hosted deployment on different vms.

Here's my `config.yml`
```
---
relay:
  upstream: "http://10.14.12.223:80"
  host: 0.0.0.0
  port: 3000
  tls_port: ~
  tls_identity_path: ~
  tls_identity_password: ~
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "10.14.12.201:9092,10.14.12.69:9092,10.14.12.126:9092"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: redis://10.14.12.239:6379
  ```
  PS.
  I tried to enable `sentry.dsn` option in the hope to see something more about this error but unfortunately I couldn't find much more in the stacktrace of the processed event:
  ```
  relay               0x55595317bcdb <unknown>
  relay               0x555953179fb3 <unknown>
  relay               0x555953179d9b <unknown>
  relay               0x55595353d046 <unknown>
  relay               0x5559535322a3 <unknown>
  relay               0x555953541b13 <unknown>
  relay               0x555953531e9e <unknown>
  relay               0x555953537c59 <unknown>
  relay               0x555953109bce <unknown>
  relay               0x55595360b49f <unknown>
  relay               0x5559529df915 <unknown>
  relay               0x5559529e3172 <unknown>
  relay               0x555952a08112 <unknown>
  relay               0x555952710ac7 <unknown>
  relay               0x5559526c1f96 <unknown>
  relay               0x5559537452f3 <unknown>
  libpthread.so.0     0x7f9160cf1fa3 start_thread
  libc.so.6           0x7f9160e1deff clone
  0x000000000000 <unknown>
  ```
  Perhaps there's a way to enable the stacktrace visibility? (I'm running the relay in a docker container)
