### ISSUE TITLE
External Relay reports rate limit without reason code

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1929]
A user with rate limiting problems sent us an extract of their Relay log, and it seems there is no `reason` being tracked:

```
2023-03-01T08:41:52Z [relay_server::actors::outcome_aggregator] TRACE: Outcome aggregation requested:
TrackOutcome { timestamp: 2023-03-01T08:41:52.837099513Z, scoping: Scoping { organization_id: ...,
project_id: ProjectId(...), project_key: ProjectKey("..."), key_id:
Some(...) }, outcome: RateLimited(None), event_id: Some(EventId(...),
remote_addr: Some(127.0.0.1), category: Error, quantity: 1 }
```

This also shows in the stats_v2 API endpoint:

```json
{
  "by": {
    "outcome": "rate_limited",
    "reason": "none"
  },
  "totals": {
    "sum(quantity)": 552830
  }
}
```

Is reason code "none" a valid one? If not, figure out how it was created.

* In Sentry, we never seem to generate a quota object without a reason code (double check).
* The only place in the Relay code base where we construct a `RateLimited` variant with reason `None` is when the envelope is empty (see below). Is this an expected code path? Why would we emit outcomes for an empty envelope for which the contents were already rate limited?

https://github.com/getsentry/relay/blob/ee8d51d4426ccc2b6e931f41c88add75e53c1ca5/relay-server/src/actors/project.rs#L748-L750

Config of the external Relay:

```yaml
relay:
  mode: managed
  upstream: "https://sentry.io/"
  host: 0.0.0.0
  port: 8080
logging:
  level: trace
  format: auto
sentry:
  enabled: true
  dsn: "..."
http:
  timeout: 65
  connection_timeout: 65
limits:
  max_concurrent_requests: 10000
  max_connection_rate: 10000
  max_session_count: 10000
```

Internal issue: https://getsentry.atlassian.net/browse/FEEDBACK-1775.
