### ISSUE TITLE
Relay not forwarding to Sentry when behind nginx proxy

### ISSUE THREAD

**Issue by DieBambusleitung** [getsentry/relay#2519]
I'm trying to use the Relay behind an nginx reverse proxy since it is recommended in the operating guidelines and for usage with ssl/https.

Unfortunately the relay seems not to forward the errors sent to it while running behind the proxy. The Relay works when sending errors directly to it without the proxy in front. I read the documentation but couldn't find anything useful except that the headers have to be set correctly, which I did in nginx configuraton. (see https://docs.sentry.io/product/relay/operating-guidelines/#request-routing) 

I think **I am missing something crucial**, but am **not able to fix it and seeking for assistance**.

Detailed information for reproduction:

System Information:
Sentry Relay Version: 23.8.0
Runtime: Docker
OS: Debian 11 bullseye

Docker-Compose File:

```yaml
version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./cert:/ssl
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: "Europe/Berlin"
  relay:
    image: getsentry/relay:latest
    command: ["run"]
    volumes:
      -  ./config/:/work/.relay/:z
    environment:
      TZ: "Europe/Berlin"
```

Sentry Relay Config:

**I also tried using the Relay in proxy mode, which also had no impact on the result.**

```yaml
relay:
  mode: managed
  upstream: https://<SENTRY_FQDN>/
  host: 0.0.0.0
  port: 3000
logging:
  level: trace
sentry:
  enable: true
```

Nginx Configuration:

```
worker_processes 1;
events { worker_connections 1024; }
http {
    server {
        listen 80;
        server_name <HOST>;

        location / {
            return 301 https://$host$request_uri;
        }
    }
    server {
        listen 443 ssl;
        server_name <HOST>;

        underscores_in_headers on;

        ssl_certificate <PATH_TO_CERT>;
        ssl_certificate_key <PATH_TO_KEY>;

        location / {
           proxy_pass   http://relay:3000;
           proxy_set_header Host $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Sentry-Auth $http_x_sentry_auth;
           proxy_set_header Content-Type $http_content_type;
           proxy_set_header User-Agent $http_user_agent;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header sentry-trace $http_sentry_trace;
           proxy_set_header baggage $http_baggage;
           proxy_set_header Access-Control-Allow-Headers "sentry-trace, baggage";
        }
    }
}
```

I attached a log from Docker for more information.
[docker.log](https://github.com/getsentry/relay/files/12646863/docker.log)
