### ISSUE TITLE
support ipv6

### ISSUE THREAD

**Issue by mmerickel** [getsentry/relay#2530]
### Environment

EKS 1.27 using IPv6

### Steps to Reproduce

`/work/.relay/config.yml`:

```yaml
"relay":
  "host": "0.0.0.0"
  "mode": "proxy"
```

Pod spec:

```yaml
spec:
  containers:
  - env:
    - name: RELAY_PORT
      value: "3000"
    image: getsentry/relay:23.9.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /api/relay/healthcheck/ready/
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    name: relay
    ports:
    - containerPort: 3000
      protocol: TCP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /api/relay/healthcheck/ready/
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    startupProbe:
      failureThreshold: 30
      httpGet:
        path: /api/relay/healthcheck/ready/
        port: 3000
        scheme: HTTP
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 2
    volumeMounts:
    - mountPath: /work/.relay/config.yml
      name: config
      readOnly: true
      subPath: config.yml
```

### Expected Result

Bind to all active interfaces, including ipv6.

### Actual Result

Healthchecks fail to `/api/relay/healthcheck/ready/`.

This config works on an IPv4 pod, only difference now is deploying on a cluster where pods only have an IPv6 address.
