### ISSUE TITLE
Unsent envelopes are not spooled to disk when stopping the relay

### ISSUE THREAD

**Issue by remod** [getsentry/relay#2661]
### Environment

* `23.10.0` Sentry relay binary
* Ubuntu 20.04 LTS

### Steps to Reproduce

1. Create Sentry relay configuration file:
   ```
   relay:
     mode: proxy
     upstream: https://<organization>.ingest.sentry.io
     host: 127.0.0.1
     port: 3000
     tls_port: null
     tls_identity_path: null
     tls_identity_password: null
   logging:
     level: trace
   spool:
     envelopes:
       path: /var/tmp/sentry_relay_spool
   ```
1. Disable your internet connection.
1. Start the relay:
   ```
   /path/to/bin/sentry_relay run --config /path/to/config/
   ```
1. Send a Sentry event from the console:
   ```
   export SENTRY_DSN='http://<project_key>@127.0.0.1:3000/<project_id>'
   sentry-cli send-event -m 'A test event'
   ```
1. Stop the relay using Ctrl+c. This triggers an error saying that the envelope was dropped:
   ```
   ERROR relay_server::actors::envelopes: error sending envelope error=could not send request to upstream error.sources=[channel closed] tags.project_key=<project_key>
   ERROR relay_server::utils::managed_envelope: dropped envelope: internal error tags.has_attachments=false tags.has_sessions=false tags.has_profiles=false tags.has_replays=false tags.has_checkins=false tags.event_category=Some(Error) cached_summary=EnvelopeSummary { event_category: Some(Error), attachment_quantity: 0, session_quantity: 0, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 6217 } recomputed_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 0, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 0 }
   ```
1. Start the relay again.
1. Enable your internet connection.
1. The event is not uploaded to Sentry.

### Expected Result

I expected that upon stopping the relay, it would write all envelopes which could not be uploaded yet to the spool file on the disk.

### Actual Result

The relay seems to drop not-yet-uploaded envelopes when stopped.

**Other situations which I've tried:**

* In a trivial setup (internet connection and relay always on), the event arrives on Sentry.
* When just disabling the internet connection, then emitting the event, and enabling the internet connection again (no relay restart in between), the event arrives on Sentry, too. So it seems that the problem is limited to restarting the relay.
