### ISSUE TITLE
Memory usage too high

### ISSUE THREAD

**Issue by elonzh** [getsentry/relay#3012]
I am deploying relay in kubernetes cluster with config like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry-relay
  namespace: sentry
  labels:
    app: sentry-relay
data:
  # https://docs.sentry.io/product/relay/options/  
  config.yml: |-
    relay:
      mode: proxy
      upstream: xxx
      host: 0.0.0.0
    logging:
      level: debug
    metrics:
      statsd: 127.0.0.1:9125
      prefix: sentry_relay
    sentry:
      enabled: true
      dsn: xxx
```

I set the memory limits to `500MiB` and it will OOM after several requests. I am wondering why the container using so much memory,I thought this program should be like a simple gateway and run with very few resources.

![image](https://github.com/getsentry/relay/assets/8749411/b228c687-4d39-4bf0-9eca-9bda2694cee7)

**Comment by elonzh** [comment]
Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-relay
  namespace: sentry
  labels:
    app: sentry-relay
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-relay
  template:
    metadata:
      name: sentry-relay
      labels:
        app: sentry-relay
    spec:
      priorityClassName: cluster-critical
      restartPolicy: Always
      initContainers:
        - name: sentry-relay-init
          image: getsentry/relay:24.1.1
          args:
            - "credentials"
            - "generate"
          volumeMounts:
            - name: credentials
              mountPath: /work/.relay
            - name: config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
              readOnly: true
      containers:
        - name: sentry-relay
          image: getsentry/relay:24.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
              name: relay
          livenessProbe:
            httpGet:
              path: /api/relay/healthcheck/live/
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/relay/healthcheck/ready/
              port: 3000
          volumeMounts:
            - name: credentials
              mountPath: /work/.relay
            - name: config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
              readOnly: true
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 500Mi
        - name: statsd-exporter
          image: prom/statsd-exporter:v0.26.0
          args:
            - --log.level=info
          ports:
            - containerPort: 9102
              protocol: TCP
              name: metrics
            - containerPort: 9125
              protocol: TCP
              name: statsd-tcp
            - containerPort: 9125
              protocol: UDP
              name: statsd-udp
          resources:
            requests:
              memory: 30Mi
            limits:
              memory: 200Mi
      volumes:
        - name: credentials
          emptyDir: { }
        - name: config
          configMap:
            name: sentry-relay
```
