### ISSUE TITLE
Can not turn off logging

### ISSUE THREAD

**Issue by garinichsan** [getsentry/relay#3051]
### Environment
- latest `getsentry/relay` image
- Run on GKE Kubernetes

### Steps to reproduce
1. Run sentry with the following configuration
```
relay:
  mode: static
  upstream: https://<organization-domain>
  host: 0.0.0.0
  port: 3000
logging:
  level: off
```

### Expected Result
Stopping the log as described in https://docs.sentry.io/product/relay/options/#logging

### Actual Result
```
caused by: logging.level: invalid value: string "off", expected a log level at line 7 column 10
```
The relay works fine when I use `info` or `error` as the log level value, but it gives me that error when I use `off` log level value
