### ISSUE TITLE
proxy mode doesn't work in 0.5.2

### ISSUE THREAD

**Issue by iluuu1994** [getsentry/relay#473]
The last version we're using successfully in production is semaphore 0.4.46.

This is my config:

```yaml
---
relay:
  mode: proxy
  upstream: "https://sentry.abc.xyz"
  host: 127.0.0.1
  port: 3000
  tls_port: ~
  tls_identity_path: ~
  tls_identity_password: ~
```

The service starts without errors.

```bash
$ export SENTRY_DSN=http://...@127.0.0.1:3000/5
$ sentry-cli send-event -m "Hello from Sentry"
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

The event is never received. The service logs no errors. It doesn't exactly help `sentry-cli send-event` doesn't even complain when the service is shut down. Switching to the real DSN works as expected.

Any idea what's going on here? How can I provide more useful information?
