### ISSUE TITLE
Relay discards events when it is offline

### ISSUE THREAD

**Issue by sxwei123** [getsentry/relay#708]
Hey there, I did some experiment on the relay `20.7.2` and found something might be wrong.
I setup the relay in `static` mode and setup the project configuration file and localhost DSN according to the documentation.

Here are the steps of my experiments:
1. Relay has Internet connection
2. Trigger an error in client SDK
3. Client SDK get 200 from relay
4. Relay forwards the error to sentry.io (I can see the events in sentry.io dashboard)

But when I try:
1. Relay disconnect to Internet
2. Trigger an error in client SDK
3. Client SDK gets 200 from relay
4. Reconnect relay to Internet
5. Can’t see the error on sentry.io dashboard.

Feel like the Relay discards the events when it is offline. According to my understanding, shouldn't it be cached until the connection to sentry.io is back or the event reaches its expiration time?

My configs:
```
cat .relay/config.yml
---
relay:
  mode: static
  upstream: "https://sentry.io/"
  host: 127.0.0.1
  port: 9000
  tls_port: ~
  tls_identity_path: ~
  tls_identity_password: ~
```

```
cat .relay/projects/xxxx.json
{
  "slug": "client-2",
  "publicKeys": [
    {
      "publicKey": "xxxxxxxxxxxxxxxxxxxx",
      "isEnabled": true
    }
  ],
  "config": {
    "allowedDomains": ["*"]
  }
}
```
