### ISSUE TITLE
Can't connect to Kafka broker using SSL

### ISSUE THREAD

**Issue by ajacques** [getsentry/relay#879]
I'm using the docker image `getsentry/relay:20.11.1`

I'm trying to connect to a Kafka broker using SSL (port 9094), but Relay is reporting that my config file is invalid.

```yaml
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
  - name: bootstrap.servers
    value: 'kafka-b-2.sentry.:9094,kafka-b-1.sentry.:9094'
  - name: security.protocol
    value: ssl
  - name: message.max.bytes
    value: 50000000
relay:
  host: 0.0.0.0
  port: 3000
  upstream: http://web.sentry.:9000
```

```
# relay -V
relay 20.11.1
# relay run
 ERROR relay::cli > could not initialize kafka producer
  caused by: Client config error: Invalid value "ssl" for configuration property "security.protocol" security.protocol ssl
```

According to the [rdkafka docs](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) this should be a legal configuration property and value. 

Rdkafka claims this is an issue with the wrapper library: edenhill/librdkafka#1938 and rust-rdkafka states that you need to compile with the openssl library: fede1024/rust-rdkafka#174. Since I'm using the getsentry/relay official Docker image, this seems it would be an issue with this repository.

So far I've been able to get the Python components (Snuba and Sentry web) to run with SSL to Kafka, so this issue appears to be limited to Relay.
