### ISSUE TITLE
Add sentry environment to sentry config section

### ISSUE THREAD

**Issue by montanaflynn** [getsentry/relay#996]
We are using sentry relay in staging and production environments and would like to have one sentry project for both of them.

This could be done by adding an `environment` field to the sentry config section:

```
    relay:
      mode: proxy
      port: 8080
    sentry: 
      enabled: true
      dsn: https://...@....ingest.sentry.io/...
      environment: staging
```

Then we could switch between environments with sentry website UI:

<img width="986" alt="Screen Shot 2021-05-17 at 17 25 06" src="https://user-images.githubusercontent.com/24260/118474072-df737400-b734-11eb-8ec1-978b10cf7066.png">
